plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.mellowpet.vision'
version = '2.0.0'

android {
  namespace "com.mellowpet.vision"
  defaultConfig {
    versionCode 1
    versionName "2.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  def cameraxVersion = '1.4.2'
  implementation "androidx.camera:camera-core:$cameraxVersion"
  implementation "androidx.camera:camera-camera2:$cameraxVersion"
  implementation "androidx.camera:camera-lifecycle:$cameraxVersion"
  implementation "androidx.camera:camera-view:$cameraxVersion"
  implementation 'com.google.mediapipe:tasks-vision:1.0.0'
}
